# This file was generated by GoReleaser. DO NOT EDIT.
class Fuzzit < Formula
  desc "Continuous Fuzzing Made Simple."
  homepage "https://fuzzit.dev"
  version "2.4.9"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/fuzzitdev/fuzzit/releases/download/v2.4.9/fuzzit_Darwin_x86_64.zip"
    sha256 "65d94ef39206bd59c2b608ae0d3044eb2b5fafb3bba88cdc21aef1030e6869e3"
  elsif OS.linux?
    url "https://github.com/fuzzitdev/fuzzit/releases/download/v2.4.9/fuzzit_Linux_x86_64.zip"
    sha256 "764e0d85f9d34ce506b5217095abf5cd9122b9cd1a9d7c338a7cc82dde8d2554"
  end

  def install
    bin.install "fuzzit"
  end
end
